### ISSUE TITLE
TypeError("'>=' not supported between instances of 'str' and 'int'") when running run.py

### ISSUE THREAD

**Issue by eelorri** [splicebox/MntJULiP#14]
Hello,
I got an error when I ran `run.py`. I don't know perl or python. Here is the error:

`mnt-JULiP: 27-Sep-24 16:29:28: Creating output folder ...
mnt-JULiP: 27-Sep-24 16:29:28: Generating splice files (or reusing splice files if save-tmp set to true and splice files exist) ...
mnt-JULiP: 27-Sep-24 16:51:12: Processing 42 samples ...
Traceback (most recent call last):
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/dataframe/utils.py", line 177, in raise_on_meta_error
    yield
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/dataframe/core.py", line 5671, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/utils.py", line 1225, in partial_by_order
    return function(*args2, **kwargs)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/arraylike.py", line 52, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/series.py", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 284, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/gage/eelorri/uORF/MntJULiP/Running_MntJULiP/run.py", line 161, in <module>
    main()
  File "/share/gage/eelorri/uORF/MntJULiP/Running_MntJULiP/run.py", line 121, in main
    end_site_genes_dict, conditions, num_threads=num_threads)
  File "/gpfs_common/share02/gage/eelorri/uORF/MntJULiP/Running_MntJULiP/utils.py", line 181, in process_introns_with_annotation
    _df = _df[_df[f"{i+1}_count"] >= 0]
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/dataframe/core.py", line 1637, in <lambda>
    return lambda self, other: elemwise(op, self, other)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/dataframe/core.py", line 5671, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/dataframe/utils.py", line 198, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `ge`.

Original error is below:
------------------------
TypeError("'>=' not supported between instances of 'str' and 'int'")

Traceback:
---------
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/dataframe/utils.py", line 177, in raise_on_meta_error
    yield
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/dataframe/core.py", line 5671, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/dask/utils.py", line 1225, in partial_by_order
    return function(*args2, **kwargs)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/arraylike.py", line 52, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/series.py", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 284, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/usr/local/usrapps/gage/eelorri/env_mntjulip/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
`
Do you know what is wrong?
Thank you for any help,
Stef

**Comment by edwwlui** [comment]
Hi eelorri, thanks for using mntjulip! It could be related to non-existing paths in your input bam-list. Could you please have a look at your input paths?

**Comment by moniwaldherr** [comment]
Hi, 
I get the exact same error message. The paths in my bam list TXT are correct for sure, they are given as absolute paths. The path to the bam list TXT I am giving as relative path. Maybe you have another idea what could be the problem?
Thanks in advance,
Monika

Update: I solved the issue by rechecking the input list, where in some lines there was no correct tab separation, but spaces, between sample path and condition field.
